import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const src = resolve('node_modules/wa-sqlite/dist/wa-sqlite.wasm');
const out = resolve('src/wispr/wasmBinary.ts');

const bytes = readFileSync(src);
if (bytes.length === 0) throw new Error('wasm file is empty');
// WASM magic number: 0x00 0x61 0x73 0x6d
if (!(bytes[0] === 0x00 && bytes[1] === 0x61 && bytes[2] === 0x73 && bytes[3] === 0x6d)) {
  throw new Error('not a valid wasm binary');
}

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/inline-wasm.mjs — do not edit.\n` +
    `// Inlined because Obsidian installs only manifest.json, main.js and styles.css.\n` +
    `export const WASM_BASE64 = '${bytes.toString('base64')}';\n`
);
console.log(`inlined ${bytes.length} bytes -> ${out}`);
